### ISSUE TITLE
possible to get rid of *scratch*

### ISSUE THREAD

**Issue by Dickby** [EricCrosson/unkillable-scratch#6]
Hi,
I found that it is still possible to get rid of the scratch buffer by saving the scratch buffer to a file.
A new scratch buffer is there if that file or buffer is deleted, but before there is no _scratch_ buffer.

**Comment by EricCrosson** [comment]
Interesting. I have never saved to a file before. Thanks for raising this!

**Comment by EricCrosson** [comment]
I do think this issue is out of scope of the package. By saving a scratch buffer to a file, it's no longer a scratch buffer!
